//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDL_Converter_Classes.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HDL_Converter_Classes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die module $NAME$
        ///$PARAMETERS$(
        ///$PORT$
        ///); ähnelt.
        /// </summary>
        internal static string VERILOG_MODULE_HEADER {
            get {
                return ResourceManager.GetString("VERILOG_MODULE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ////////////////////////////////////////////////////////////////////////////
        /////
        ///// Name: $NAME$
        ///// Description:
        /////
        ///// Version: 1.0.0
        ///// Date: $DATE$
        /////
        ///// Company: 
        ///// Engineer:
        ///// 
        ///////////////////////////////////////////////////////////////////////////////
        ///
        ///module $NAME$
        ///#(
        ///$PARAMETERS$
        ///)
        ///(
        ///$PORT$
        ///);
        /////========================================================
        ///// Wire Declarations
        /////========================================================
        ///
        ///$WIREDECLARATIONS$
        ///
        /////==================== [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string VERILOG_MODULE_SYNTAX {
            get {
                return ResourceManager.GetString("VERILOG_MODULE_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ////////////////////////////////////////////////////////////////////////////
        /////
        ///// Name: $NAME$
        ///// Description:
        /////
        ///// Version: 1.0.0
        ///// Date: $DATE$
        /////
        ///// Company: 
        ///// Engineer:
        ///// 
        ///////////////////////////////////////////////////////////////////////////////
        ///
        ///$HEADER$
        /////========================================================
        ///// Wire Declarations
        /////========================================================
        ///
        ///$WIREDECLARATIONS$
        ///
        /////========================================================
        /////  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string VERILOG_TEMPLATE_NO_HEADER {
            get {
                return ResourceManager.GetString("VERILOG_TEMPLATE_NO_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ////////////////////////////////////////////////////////////////////////////
        /////
        ///// Name: $NAME$
        ///// Description:
        /////
        ///// Version: 1.0.0
        ///// Date: $DATE$
        /////
        ///// Company: 
        ///// Engineer:
        ///// 
        ///////////////////////////////////////////////////////////////////////////////
        ///
        ///module $NAME$();
        /////========================================================
        ///// Constants
        /////========================================================
        ///
        ///$CONSTANTS$
        ///
        /////========================================================
        ///// Wire De [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string VERILOG_TESTBENCH_TOP {
            get {
                return ResourceManager.GetString("VERILOG_TESTBENCH_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die component $NAME$ is
        ///$PARAMETERS$$PORT$
        ///end component $NAME$; ähnelt.
        /// </summary>
        internal static string VHDL_COMPONENT {
            get {
                return ResourceManager.GetString("VHDL_COMPONENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die entity $NAME$ is
        ///$PARAMETERS$$PORT$
        ///end entity $NAME$; ähnelt.
        /// </summary>
        internal static string VHDL_ENTITY {
            get {
                return ResourceManager.GetString("VHDL_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die inst_$NAME$ : component $NAME$
        ///$PARAMETERS$$PORT$; ähnelt.
        /// </summary>
        internal static string VHDL_INSTANCE {
            get {
                return ResourceManager.GetString("VHDL_INSTANCE", resourceCulture);
            }
        }
    }
}
